POST http://localhost:3000/stocks.json
Content-Type: application/json

{
  "symbol": "UUUU",
  "company_name": "Energy Fuels",
  "cost_basis": 3.5,
  "current_price": 9,
  "quantity": 20,
  "sector_id": 3,
  "industry_id": 2
}

###DESTROY
DELETE http://localhost:3000/stocks/7.json
